/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../../../..";

export interface CompletionsStreamRequest {
    userIdentifier: string;
    groupIdentifier?: string;
    model?: string;
    query?: string;
    context?: DoptApi.assistant.CompletionsStreamRequestContext;
}
