/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";
import { SearchRequestContextDocumentValue } from "./SearchRequestContextDocumentValue";

export const SearchRequestContextDocument: core.serialization.ObjectSchema<
    serializers.SearchRequestContextDocument.Raw,
    DoptApi.SearchRequestContextDocument
> = core.serialization.object({
    type: core.serialization.stringLiteral("document"),
    value: SearchRequestContextDocumentValue,
});

export declare namespace SearchRequestContextDocument {
    interface Raw {
        type: "document";
        value: SearchRequestContextDocumentValue.Raw;
    }
}
