/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";
import { SearchResponseItemChunksItem } from "./SearchResponseItemChunksItem";

export const SearchResponseItem: core.serialization.ObjectSchema<
    serializers.SearchResponseItem.Raw,
    DoptApi.SearchResponseItem
> = core.serialization.object({
    id: core.serialization.number(),
    title: core.serialization.string(),
    url: core.serialization.string(),
    chunks: core.serialization.list(SearchResponseItemChunksItem),
});

export declare namespace SearchResponseItem {
    interface Raw {
        id: number;
        title: string;
        url: string;
        chunks: SearchResponseItemChunksItem.Raw[];
    }
}
