/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";
import { SearchRequestContextElementValue } from "./SearchRequestContextElementValue";

export const SearchRequestContextElement: core.serialization.ObjectSchema<
    serializers.SearchRequestContextElement.Raw,
    DoptApi.SearchRequestContextElement
> = core.serialization.object({
    type: core.serialization.stringLiteral("element"),
    value: SearchRequestContextElementValue,
});

export declare namespace SearchRequestContextElement {
    interface Raw {
        type: "element";
        value: SearchRequestContextElementValue.Raw;
    }
}
