/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as DoptApi from "../../../../api";
import * as core from "../../../../core";

export const SearchRequestContextDocument: core.serialization.ObjectSchema<
    serializers.SearchRequestContextDocument.Raw,
    DoptApi.SearchRequestContextDocument
> = core.serialization.object({
    type: core.serialization.stringLiteral("document"),
    value: core.serialization.lazyObject(async () => (await import("../../..")).SearchRequestContextDocumentValue),
});

export declare namespace SearchRequestContextDocument {
    interface Raw {
        type: "document";
        value: serializers.SearchRequestContextDocumentValue.Raw;
    }
}
