/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";
import { SearchRequestContextSemanticValue } from "./SearchRequestContextSemanticValue";

export const SearchRequestContextSemantic: core.serialization.ObjectSchema<
    serializers.SearchRequestContextSemantic.Raw,
    DoptApi.SearchRequestContextSemantic
> = core.serialization.object({
    type: core.serialization.stringLiteral("semantic"),
    value: SearchRequestContextSemanticValue,
});

export declare namespace SearchRequestContextSemantic {
    interface Raw {
        type: "semantic";
        value: SearchRequestContextSemanticValue.Raw;
    }
}
