/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as DoptApi from "../../../../api";
import * as core from "../../../../core";

export const SearchRequestContextElementValue: core.serialization.ObjectSchema<
    serializers.SearchRequestContextElementValue.Raw,
    DoptApi.SearchRequestContextElementValue
> = core.serialization.object({
    position: core.serialization.lazyObject(
        async () => (await import("../../..")).SearchRequestContextElementValuePosition
    ),
    content: core.serialization.string(),
    tag: core.serialization.string(),
});

export declare namespace SearchRequestContextElementValue {
    interface Raw {
        position: serializers.SearchRequestContextElementValuePosition.Raw;
        content: string;
        tag: string;
    }
}
