/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as DoptApi from "../../../../api";
import * as core from "../../../../core";

export const SearchRequestContextElement: core.serialization.ObjectSchema<
    serializers.SearchRequestContextElement.Raw,
    DoptApi.SearchRequestContextElement
> = core.serialization.object({
    type: core.serialization.stringLiteral("element"),
    value: core.serialization.lazyObject(async () => (await import("../../..")).SearchRequestContextElementValue),
});

export declare namespace SearchRequestContextElement {
    interface Raw {
        type: "element";
        value: serializers.SearchRequestContextElementValue.Raw;
    }
}
