/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";
import { SearchRequestContextElementValuePosition } from "./SearchRequestContextElementValuePosition";

export const SearchRequestContextElementValue: core.serialization.ObjectSchema<
    serializers.SearchRequestContextElementValue.Raw,
    DoptApi.SearchRequestContextElementValue
> = core.serialization.object({
    position: SearchRequestContextElementValuePosition,
    content: core.serialization.string(),
    tag: core.serialization.string(),
});

export declare namespace SearchRequestContextElementValue {
    interface Raw {
        position: SearchRequestContextElementValuePosition.Raw;
        content: string;
        tag: string;
    }
}
