/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";

export const SearchRequestContextVisual: core.serialization.ObjectSchema<
    serializers.SearchRequestContextVisual.Raw,
    DoptApi.SearchRequestContextVisual
> = core.serialization.object({
    type: core.serialization.stringLiteral("visual"),
    value: core.serialization.string(),
});

export declare namespace SearchRequestContextVisual {
    interface Raw {
        type: "visual";
        value: string;
    }
}
