/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";

export const SearchRequestContextElementValuePosition: core.serialization.ObjectSchema<
    serializers.SearchRequestContextElementValuePosition.Raw,
    DoptApi.SearchRequestContextElementValuePosition
> = core.serialization.object({
    top: core.serialization.number(),
    left: core.serialization.number(),
});

export declare namespace SearchRequestContextElementValuePosition {
    interface Raw {
        top: number;
        left: number;
    }
}
