/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as DoptApi from "../../../../api";
import * as core from "../../../../core";

export const SearchRequestContext: core.serialization.ObjectSchema<
    serializers.SearchRequestContext.Raw,
    DoptApi.SearchRequestContext
> = core.serialization.object({
    document: core.serialization
        .lazyObject(async () => (await import("../../..")).SearchRequestContextDocument)
        .optional(),
    visual: core.serialization.lazyObject(async () => (await import("../../..")).SearchRequestContextVisual).optional(),
    element: core.serialization
        .lazyObject(async () => (await import("../../..")).SearchRequestContextElement)
        .optional(),
    semantic: core.serialization
        .lazyObject(async () => (await import("../../..")).SearchRequestContextSemantic)
        .optional(),
});

export declare namespace SearchRequestContext {
    interface Raw {
        document?: serializers.SearchRequestContextDocument.Raw | null;
        visual?: serializers.SearchRequestContextVisual.Raw | null;
        element?: serializers.SearchRequestContextElement.Raw | null;
        semantic?: serializers.SearchRequestContextSemantic.Raw | null;
    }
}
