/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as DoptApi from "../../../../api";
import * as core from "../../../../core";

export const SearchRequestContextDocumentValue: core.serialization.ObjectSchema<
    serializers.SearchRequestContextDocumentValue.Raw,
    DoptApi.SearchRequestContextDocumentValue
> = core.serialization.object({
    url: core.serialization.string(),
    title: core.serialization.string(),
    width: core.serialization.number(),
    height: core.serialization.number(),
});

export declare namespace SearchRequestContextDocumentValue {
    interface Raw {
        url: string;
        title: string;
        width: number;
        height: number;
    }
}
