/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as DoptApi from "../../../../api";
import * as core from "../../../../core";

export const SearchRequestContextSemantic: core.serialization.ObjectSchema<
    serializers.SearchRequestContextSemantic.Raw,
    DoptApi.SearchRequestContextSemantic
> = core.serialization.object({
    type: core.serialization.stringLiteral("semantic"),
    value: core.serialization.lazyObject(async () => (await import("../../..")).SearchRequestContextSemanticValue),
});

export declare namespace SearchRequestContextSemantic {
    interface Raw {
        type: "semantic";
        value: serializers.SearchRequestContextSemanticValue.Raw;
    }
}
