/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";

export const SearchRequestContextSemanticValue: core.serialization.ObjectSchema<
    serializers.SearchRequestContextSemanticValue.Raw,
    DoptApi.SearchRequestContextSemanticValue
> = core.serialization.object({
    semanticContent: core.serialization.string(),
    neighboringSemanticContent: core.serialization.string(),
});

export declare namespace SearchRequestContextSemanticValue {
    interface Raw {
        semanticContent: string;
        neighboringSemanticContent: string;
    }
}
