/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as DoptApi from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { CompletionsStreamRequestContext } from "../../types/CompletionsStreamRequestContext";

export const CompletionsStreamRequest: core.serialization.Schema<
    serializers.assistant.CompletionsStreamRequest.Raw,
    Omit<DoptApi.assistant.CompletionsStreamRequest, "userIdentifier" | "groupIdentifier" | "model">
> = core.serialization.object({
    query: core.serialization.string().optional(),
    context: CompletionsStreamRequestContext.optional(),
});

export declare namespace CompletionsStreamRequest {
    interface Raw {
        query?: string | null;
        context?: CompletionsStreamRequestContext.Raw | null;
    }
}
