/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../..";
import * as DoptApi from "../../../../../../../api";
import * as core from "../../../../../../../core";

export const CompletionsCreateRequest: core.serialization.Schema<
    serializers.assistant.CompletionsCreateRequest.Raw,
    Omit<DoptApi.assistant.CompletionsCreateRequest, "userIdentifier" | "groupIdentifier" | "model">
> = core.serialization.object({
    query: core.serialization.string().optional(),
    context: core.serialization
        .lazyObject(async () => (await import("../../../../../..")).assistant.CompletionsCreateRequestContext)
        .optional(),
});

export declare namespace CompletionsCreateRequest {
    interface Raw {
        query?: string | null;
        context?: serializers.assistant.CompletionsCreateRequestContext.Raw | null;
    }
}
