/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as DoptApi from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { CompletionsCreateRequestContext } from "../../types/CompletionsCreateRequestContext";

export const CompletionsCreateRequest: core.serialization.Schema<
    serializers.assistant.CompletionsCreateRequest.Raw,
    Omit<DoptApi.assistant.CompletionsCreateRequest, "userIdentifier" | "groupIdentifier" | "model">
> = core.serialization.object({
    query: core.serialization.string().optional(),
    context: CompletionsCreateRequestContext.optional(),
});

export declare namespace CompletionsCreateRequest {
    interface Raw {
        query?: string | null;
        context?: CompletionsCreateRequestContext.Raw | null;
    }
}
