/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SearchRequestContextDocumentValue {
    url: string;
    title: string;
    width: number;
    height: number;
}
