/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../index";

export interface SearchRequestContext {
    document?: DoptApi.SearchRequestContextDocument;
    visual?: DoptApi.SearchRequestContextVisual;
    element?: DoptApi.SearchRequestContextElement;
    semantic?: DoptApi.SearchRequestContextSemantic;
}
