/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../..";

export interface SearchRequestContextElementValue {
    position: DoptApi.SearchRequestContextElementValuePosition;
    content: string;
    tag: string;
}
