/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../index";

export interface AnswerChunk {
    type: "answer";
    answer: string;
    sources: DoptApi.AnswerChunkSourcesItem[];
}
