/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../index";

export interface AssistantRequestBodyContextElementValue {
    position: DoptApi.AssistantRequestBodyContextElementValuePosition;
    content: string;
    tag: string;
}
