/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../index";

export interface AssistantSearchRequestBodyContext {
    document?: DoptApi.AssistantSearchRequestBodyContextDocument;
    visual?: DoptApi.AssistantSearchRequestBodyContextVisual;
    element?: DoptApi.AssistantSearchRequestBodyContextElement;
    semantic?: DoptApi.AssistantSearchRequestBodyContextSemantic;
}
