/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "..";

export interface AssistantRequestBodyContext {
    document?: DoptApi.AssistantRequestBodyContextDocument;
    visual?: DoptApi.AssistantRequestBodyContextVisual;
    element?: DoptApi.AssistantRequestBodyContextElement;
    semantic?: DoptApi.AssistantRequestBodyContextSemantic;
}
