/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "..";

export interface AssistantCompletionsRequestBodyContext {
    document?: DoptApi.AssistantCompletionsRequestBodyContextDocument;
    visual?: DoptApi.AssistantCompletionsRequestBodyContextVisual;
    element?: DoptApi.AssistantCompletionsRequestBodyContextElement;
    semantic?: DoptApi.AssistantCompletionsRequestBodyContextSemantic;
}
