/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../index";

export interface AssistantDocumentSourcesItem {
    id: number;
    title: string;
    url: string;
    chunks: DoptApi.AssistantDocumentSourcesItemChunksItem[];
}
