/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AssistantCompletionsResponseSourcesItemChunksItem {
    chunkId: number;
    text: string;
    score: number;
}
