/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "..";

export interface AssistantSearchRequestBody {
    query?: string;
    context?: DoptApi.AssistantSearchRequestBodyContext;
}
