/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../index";

export interface AssistantSearchRequestBodyContextElement {
    type: "element";
    value: DoptApi.AssistantSearchRequestBodyContextElementValue;
}
