/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "..";

export interface AssistantCompletionsRequestBodyContextElementValue {
    position: DoptApi.AssistantCompletionsRequestBodyContextElementValuePosition;
    content: string;
    tag: string;
}
