/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "..";

export interface AssistantSearchRequestBodyContextElementValue {
    position: DoptApi.AssistantSearchRequestBodyContextElementValuePosition;
    content: string;
    tag: string;
}
