/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../index";

export interface AssistantRequestBodyContextElement {
    type: "element";
    value: DoptApi.AssistantRequestBodyContextElementValue;
}
