/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AssistantCompletionsRequestBodyContextSemanticValue {
    semanticContent: string;
    neighboringSemanticContent: string;
}
