/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ChatStreamChunkStatusStatus = "searching" | "answering";

export const ChatStreamChunkStatusStatus = {
    Searching: "searching",
    Answering: "answering",
} as const;
