/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../index";

export interface DocumentContext {
    type: "document";
    value: DoptApi.DocumentContextValue;
}
