/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../index";

export interface ElementContextValue {
    position: DoptApi.ElementContextValuePosition;
    content: string;
    tag: string;
}
