/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type StatusChunkStatus = "searching" | "answering";

export const StatusChunkStatus = {
    Searching: "searching",
    Answering: "answering",
} as const;
