/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../../index";

/**
 * @example
 *     {
 *         userIdentifier: "userIdentifier"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         model: "string"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         model: "string"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         model: "string"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         model: "string"
 *     }
 *
 * @example
 *     {
 *         userIdentifier: "string",
 *         groupIdentifier: "string",
 *         model: "string"
 *     }
 */
export interface SearchRequest {
    userIdentifier: string;
    groupIdentifier?: string;
    model?: string;
    query?: string;
    context?: DoptApi.SearchRequestContext;
}
