/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as DoptApi from "../../../../../api";
import * as core from "../../../../../core";

export const SearchRequest: core.serialization.Schema<
    serializers.SearchRequest.Raw,
    Omit<DoptApi.SearchRequest, "userIdentifier" | "groupIdentifier" | "model">
> = core.serialization.object({
    query: core.serialization.string().optional(),
    context: core.serialization.lazyObject(async () => (await import("../../../..")).SearchRequestContext).optional(),
});

export declare namespace SearchRequest {
    interface Raw {
        query?: string | null;
        context?: serializers.SearchRequestContext.Raw | null;
    }
}
