/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DoptApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { SearchRequestContext } from "../../types/SearchRequestContext";

export const SearchRequest: core.serialization.Schema<
    serializers.SearchRequest.Raw,
    Omit<DoptApi.SearchRequest, "userIdentifier" | "groupIdentifier" | "model">
> = core.serialization.object({
    query: core.serialization.string().optional(),
    context: SearchRequestContext.optional(),
});

export declare namespace SearchRequest {
    interface Raw {
        query?: string | null;
        context?: SearchRequestContext.Raw | null;
    }
}
