/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CompletionsStreamResponseStatusStatus = "searching" | "answering";

export const CompletionsStreamResponseStatusStatus = {
    Searching: "searching",
    Answering: "answering",
} as const;
