/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../../../index";

export interface CompletionsStreamRequestContextDocument {
    type: "document";
    value: DoptApi.assistant.CompletionsStreamRequestContextDocumentValue;
}
