/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../../..";

export interface CompletionsStreamRequestContextSemantic {
    type: "semantic";
    value: DoptApi.assistant.CompletionsStreamRequestContextSemanticValue;
}
