/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../../..";

export interface CompletionsStreamRequestContext {
    document?: DoptApi.assistant.CompletionsStreamRequestContextDocument;
    visual?: DoptApi.assistant.CompletionsStreamRequestContextVisual;
    element?: DoptApi.assistant.CompletionsStreamRequestContextElement;
    semantic?: DoptApi.assistant.CompletionsStreamRequestContextSemantic;
}
