/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../../../index";

export interface CompletionsCreateRequestContext {
    document?: DoptApi.assistant.CompletionsCreateRequestContextDocument;
    visual?: DoptApi.assistant.CompletionsCreateRequestContextVisual;
    element?: DoptApi.assistant.CompletionsCreateRequestContextElement;
    semantic?: DoptApi.assistant.CompletionsCreateRequestContextSemantic;
}
