/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../../..";

export interface CompletionsCreateResponseSourcesItem {
    id: number;
    title: string;
    url: string;
    chunks: DoptApi.assistant.CompletionsCreateResponseSourcesItemChunksItem[];
}
