/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../../..";

export interface CompletionsStreamRequestContextElement {
    type: "element";
    value: DoptApi.assistant.CompletionsStreamRequestContextElementValue;
}
