/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../../..";

export interface CompletionsStreamRequestContextElementValue {
    position: DoptApi.assistant.CompletionsStreamRequestContextElementValuePosition;
    content: string;
    tag: string;
}
