/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../../../index";

export type CompletionsStreamResponse =
    | DoptApi.assistant.CompletionsStreamResponse.Status
    | DoptApi.assistant.CompletionsStreamResponse.Content
    | DoptApi.assistant.CompletionsStreamResponse.Answer;

export declare namespace CompletionsStreamResponse {
    interface Status extends DoptApi.assistant.CompletionsStreamResponseStatus {
        type: "status";
    }

    interface Content extends DoptApi.assistant.CompletionsStreamResponseContent {
        type: "content";
    }

    interface Answer extends DoptApi.assistant.CompletionsStreamResponseAnswer {
        type: "answer";
    }
}
