/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AnswerChunkSourcesItemChunksItem } from "./AnswerChunkSourcesItemChunksItem";

export const AnswerChunkSourcesItem: core.serialization.ObjectSchema<
    serializers.AnswerChunkSourcesItem.Raw,
    DoptApi.AnswerChunkSourcesItem
> = core.serialization.object({
    id: core.serialization.number(),
    title: core.serialization.string(),
    url: core.serialization.string(),
    chunks: core.serialization.list(AnswerChunkSourcesItemChunksItem),
});

export declare namespace AnswerChunkSourcesItem {
    interface Raw {
        id: number;
        title: string;
        url: string;
        chunks: AnswerChunkSourcesItemChunksItem.Raw[];
    }
}
