/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AnswerChunkSourcesItem } from "./AnswerChunkSourcesItem";

export const AnswerChunk: core.serialization.ObjectSchema<serializers.AnswerChunk.Raw, DoptApi.AnswerChunk> =
    core.serialization.object({
        type: core.serialization.stringLiteral("answer"),
        answer: core.serialization.string(),
        sources: core.serialization.list(AnswerChunkSourcesItem),
    });

export declare namespace AnswerChunk {
    interface Raw {
        type: "answer";
        answer: string;
        sources: AnswerChunkSourcesItem.Raw[];
    }
}
