/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AnswerChunk: core.serialization.ObjectSchema<serializers.AnswerChunk.Raw, DoptApi.AnswerChunk> =
    core.serialization.object({
        type: core.serialization.stringLiteral("answer"),
        answer: core.serialization.string(),
        sources: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("..")).AnswerChunkSourcesItem)
        ),
    });

export declare namespace AnswerChunk {
    interface Raw {
        type: "answer";
        answer: string;
        sources: serializers.AnswerChunkSourcesItem.Raw[];
    }
}
