/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantRequestParams: core.serialization.ObjectSchema<
    serializers.AssistantRequestParams.Raw,
    DoptApi.AssistantRequestParams
> = core.serialization.object({
    sid: core.serialization.string(),
});

export declare namespace AssistantRequestParams {
    interface Raw {
        sid: string;
    }
}
