/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantSearchRequestBodyContextDocument: core.serialization.ObjectSchema<
    serializers.AssistantSearchRequestBodyContextDocument.Raw,
    DoptApi.AssistantSearchRequestBodyContextDocument
> = core.serialization.object({
    type: core.serialization.stringLiteral("document"),
    value: core.serialization.lazyObject(
        async () => (await import("..")).AssistantSearchRequestBodyContextDocumentValue
    ),
});

export declare namespace AssistantSearchRequestBodyContextDocument {
    interface Raw {
        type: "document";
        value: serializers.AssistantSearchRequestBodyContextDocumentValue.Raw;
    }
}
