/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantCompletionsResponseSourcesItemChunksItem } from "./AssistantCompletionsResponseSourcesItemChunksItem";

export const AssistantCompletionsResponseSourcesItem: core.serialization.ObjectSchema<
    serializers.AssistantCompletionsResponseSourcesItem.Raw,
    DoptApi.AssistantCompletionsResponseSourcesItem
> = core.serialization.object({
    id: core.serialization.number(),
    title: core.serialization.string(),
    url: core.serialization.string(),
    chunks: core.serialization.list(AssistantCompletionsResponseSourcesItemChunksItem),
});

export declare namespace AssistantCompletionsResponseSourcesItem {
    interface Raw {
        id: number;
        title: string;
        url: string;
        chunks: AssistantCompletionsResponseSourcesItemChunksItem.Raw[];
    }
}
