/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantRequestBodyContextDocument } from "./AssistantRequestBodyContextDocument";
import { AssistantRequestBodyContextVisual } from "./AssistantRequestBodyContextVisual";
import { AssistantRequestBodyContextElement } from "./AssistantRequestBodyContextElement";
import { AssistantRequestBodyContextSemantic } from "./AssistantRequestBodyContextSemantic";

export const AssistantRequestBodyContext: core.serialization.ObjectSchema<
    serializers.AssistantRequestBodyContext.Raw,
    DoptApi.AssistantRequestBodyContext
> = core.serialization.object({
    document: AssistantRequestBodyContextDocument.optional(),
    visual: AssistantRequestBodyContextVisual.optional(),
    element: AssistantRequestBodyContextElement.optional(),
    semantic: AssistantRequestBodyContextSemantic.optional(),
});

export declare namespace AssistantRequestBodyContext {
    interface Raw {
        document?: AssistantRequestBodyContextDocument.Raw | null;
        visual?: AssistantRequestBodyContextVisual.Raw | null;
        element?: AssistantRequestBodyContextElement.Raw | null;
        semantic?: AssistantRequestBodyContextSemantic.Raw | null;
    }
}
