/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";

export const AssistantSearchResponseItemChunksItem: core.serialization.ObjectSchema<
    serializers.AssistantSearchResponseItemChunksItem.Raw,
    DoptApi.AssistantSearchResponseItemChunksItem
> = core.serialization.object({
    chunkId: core.serialization.number(),
    text: core.serialization.string(),
    score: core.serialization.number(),
});

export declare namespace AssistantSearchResponseItemChunksItem {
    interface Raw {
        chunkId: number;
        text: string;
        score: number;
    }
}
