/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantSearchRequestBodyContextDocument } from "./AssistantSearchRequestBodyContextDocument";
import { AssistantSearchRequestBodyContextVisual } from "./AssistantSearchRequestBodyContextVisual";
import { AssistantSearchRequestBodyContextElement } from "./AssistantSearchRequestBodyContextElement";
import { AssistantSearchRequestBodyContextSemantic } from "./AssistantSearchRequestBodyContextSemantic";

export const AssistantSearchRequestBodyContext: core.serialization.ObjectSchema<
    serializers.AssistantSearchRequestBodyContext.Raw,
    DoptApi.AssistantSearchRequestBodyContext
> = core.serialization.object({
    document: AssistantSearchRequestBodyContextDocument.optional(),
    visual: AssistantSearchRequestBodyContextVisual.optional(),
    element: AssistantSearchRequestBodyContextElement.optional(),
    semantic: AssistantSearchRequestBodyContextSemantic.optional(),
});

export declare namespace AssistantSearchRequestBodyContext {
    interface Raw {
        document?: AssistantSearchRequestBodyContextDocument.Raw | null;
        visual?: AssistantSearchRequestBodyContextVisual.Raw | null;
        element?: AssistantSearchRequestBodyContextElement.Raw | null;
        semantic?: AssistantSearchRequestBodyContextSemantic.Raw | null;
    }
}
