/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantRequestBodyContextSemantic: core.serialization.ObjectSchema<
    serializers.AssistantRequestBodyContextSemantic.Raw,
    DoptApi.AssistantRequestBodyContextSemantic
> = core.serialization.object({
    type: core.serialization.stringLiteral("semantic"),
    value: core.serialization.lazyObject(async () => (await import("..")).AssistantRequestBodyContextSemanticValue),
});

export declare namespace AssistantRequestBodyContextSemantic {
    interface Raw {
        type: "semantic";
        value: serializers.AssistantRequestBodyContextSemanticValue.Raw;
    }
}
