/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantCompletionsRequestBodyContext: core.serialization.ObjectSchema<
    serializers.AssistantCompletionsRequestBodyContext.Raw,
    DoptApi.AssistantCompletionsRequestBodyContext
> = core.serialization.object({
    document: core.serialization
        .lazyObject(async () => (await import("..")).AssistantCompletionsRequestBodyContextDocument)
        .optional(),
    visual: core.serialization
        .lazyObject(async () => (await import("..")).AssistantCompletionsRequestBodyContextVisual)
        .optional(),
    element: core.serialization
        .lazyObject(async () => (await import("..")).AssistantCompletionsRequestBodyContextElement)
        .optional(),
    semantic: core.serialization
        .lazyObject(async () => (await import("..")).AssistantCompletionsRequestBodyContextSemantic)
        .optional(),
});

export declare namespace AssistantCompletionsRequestBodyContext {
    interface Raw {
        document?: serializers.AssistantCompletionsRequestBodyContextDocument.Raw | null;
        visual?: serializers.AssistantCompletionsRequestBodyContextVisual.Raw | null;
        element?: serializers.AssistantCompletionsRequestBodyContextElement.Raw | null;
        semantic?: serializers.AssistantCompletionsRequestBodyContextSemantic.Raw | null;
    }
}
