/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantCompletionsRequestBodyContextDocument } from "./AssistantCompletionsRequestBodyContextDocument";
import { AssistantCompletionsRequestBodyContextVisual } from "./AssistantCompletionsRequestBodyContextVisual";
import { AssistantCompletionsRequestBodyContextElement } from "./AssistantCompletionsRequestBodyContextElement";
import { AssistantCompletionsRequestBodyContextSemantic } from "./AssistantCompletionsRequestBodyContextSemantic";

export const AssistantCompletionsRequestBodyContext: core.serialization.ObjectSchema<
    serializers.AssistantCompletionsRequestBodyContext.Raw,
    DoptApi.AssistantCompletionsRequestBodyContext
> = core.serialization.object({
    document: AssistantCompletionsRequestBodyContextDocument.optional(),
    visual: AssistantCompletionsRequestBodyContextVisual.optional(),
    element: AssistantCompletionsRequestBodyContextElement.optional(),
    semantic: AssistantCompletionsRequestBodyContextSemantic.optional(),
});

export declare namespace AssistantCompletionsRequestBodyContext {
    interface Raw {
        document?: AssistantCompletionsRequestBodyContextDocument.Raw | null;
        visual?: AssistantCompletionsRequestBodyContextVisual.Raw | null;
        element?: AssistantCompletionsRequestBodyContextElement.Raw | null;
        semantic?: AssistantCompletionsRequestBodyContextSemantic.Raw | null;
    }
}
