/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantCompletionsRequestBodyContextElementValue } from "./AssistantCompletionsRequestBodyContextElementValue";

export const AssistantCompletionsRequestBodyContextElement: core.serialization.ObjectSchema<
    serializers.AssistantCompletionsRequestBodyContextElement.Raw,
    DoptApi.AssistantCompletionsRequestBodyContextElement
> = core.serialization.object({
    type: core.serialization.stringLiteral("element"),
    value: AssistantCompletionsRequestBodyContextElementValue,
});

export declare namespace AssistantCompletionsRequestBodyContextElement {
    interface Raw {
        type: "element";
        value: AssistantCompletionsRequestBodyContextElementValue.Raw;
    }
}
