/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantSearchRequestBodyContextSemantic: core.serialization.ObjectSchema<
    serializers.AssistantSearchRequestBodyContextSemantic.Raw,
    DoptApi.AssistantSearchRequestBodyContextSemantic
> = core.serialization.object({
    type: core.serialization.stringLiteral("semantic"),
    value: core.serialization.lazyObject(
        async () => (await import("..")).AssistantSearchRequestBodyContextSemanticValue
    ),
});

export declare namespace AssistantSearchRequestBodyContextSemantic {
    interface Raw {
        type: "semantic";
        value: serializers.AssistantSearchRequestBodyContextSemanticValue.Raw;
    }
}
