/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantRequestBodyContextElementValue: core.serialization.ObjectSchema<
    serializers.AssistantRequestBodyContextElementValue.Raw,
    DoptApi.AssistantRequestBodyContextElementValue
> = core.serialization.object({
    position: core.serialization.lazyObject(
        async () => (await import("..")).AssistantRequestBodyContextElementValuePosition
    ),
    content: core.serialization.string(),
    tag: core.serialization.string(),
});

export declare namespace AssistantRequestBodyContextElementValue {
    interface Raw {
        position: serializers.AssistantRequestBodyContextElementValuePosition.Raw;
        content: string;
        tag: string;
    }
}
