/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantCompletionsRequestBodyContextSemanticValue } from "./AssistantCompletionsRequestBodyContextSemanticValue";

export const AssistantCompletionsRequestBodyContextSemantic: core.serialization.ObjectSchema<
    serializers.AssistantCompletionsRequestBodyContextSemantic.Raw,
    DoptApi.AssistantCompletionsRequestBodyContextSemantic
> = core.serialization.object({
    type: core.serialization.stringLiteral("semantic"),
    value: AssistantCompletionsRequestBodyContextSemanticValue,
});

export declare namespace AssistantCompletionsRequestBodyContextSemantic {
    interface Raw {
        type: "semantic";
        value: AssistantCompletionsRequestBodyContextSemanticValue.Raw;
    }
}
