/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantRequestBodyContextSemanticValue: core.serialization.ObjectSchema<
    serializers.AssistantRequestBodyContextSemanticValue.Raw,
    DoptApi.AssistantRequestBodyContextSemanticValue
> = core.serialization.object({
    semanticContent: core.serialization.string(),
    neighboringSemanticContent: core.serialization.string(),
});

export declare namespace AssistantRequestBodyContextSemanticValue {
    interface Raw {
        semanticContent: string;
        neighboringSemanticContent: string;
    }
}
