/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantSearchRequestBodyContextElementValue: core.serialization.ObjectSchema<
    serializers.AssistantSearchRequestBodyContextElementValue.Raw,
    DoptApi.AssistantSearchRequestBodyContextElementValue
> = core.serialization.object({
    position: core.serialization.lazyObject(
        async () => (await import("..")).AssistantSearchRequestBodyContextElementValuePosition
    ),
    content: core.serialization.string(),
    tag: core.serialization.string(),
});

export declare namespace AssistantSearchRequestBodyContextElementValue {
    interface Raw {
        position: serializers.AssistantSearchRequestBodyContextElementValuePosition.Raw;
        content: string;
        tag: string;
    }
}
