/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantSearchRequestBodyContextElementValue } from "./AssistantSearchRequestBodyContextElementValue";

export const AssistantSearchRequestBodyContextElement: core.serialization.ObjectSchema<
    serializers.AssistantSearchRequestBodyContextElement.Raw,
    DoptApi.AssistantSearchRequestBodyContextElement
> = core.serialization.object({
    type: core.serialization.stringLiteral("element"),
    value: AssistantSearchRequestBodyContextElementValue,
});

export declare namespace AssistantSearchRequestBodyContextElement {
    interface Raw {
        type: "element";
        value: AssistantSearchRequestBodyContextElementValue.Raw;
    }
}
