/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantSearchRequestBodyContext } from "./AssistantSearchRequestBodyContext";

export const AssistantSearchRequestBody: core.serialization.ObjectSchema<
    serializers.AssistantSearchRequestBody.Raw,
    DoptApi.AssistantSearchRequestBody
> = core.serialization.object({
    query: core.serialization.string().optional(),
    context: AssistantSearchRequestBodyContext.optional(),
});

export declare namespace AssistantSearchRequestBody {
    interface Raw {
        query?: string | null;
        context?: AssistantSearchRequestBodyContext.Raw | null;
    }
}
