/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantSearchRequestBodyContextSemanticValue } from "./AssistantSearchRequestBodyContextSemanticValue";

export const AssistantSearchRequestBodyContextSemantic: core.serialization.ObjectSchema<
    serializers.AssistantSearchRequestBodyContextSemantic.Raw,
    DoptApi.AssistantSearchRequestBodyContextSemantic
> = core.serialization.object({
    type: core.serialization.stringLiteral("semantic"),
    value: AssistantSearchRequestBodyContextSemanticValue,
});

export declare namespace AssistantSearchRequestBodyContextSemantic {
    interface Raw {
        type: "semantic";
        value: AssistantSearchRequestBodyContextSemanticValue.Raw;
    }
}
