/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";

export const AssistantQueryParams: core.serialization.ObjectSchema<
    serializers.AssistantQueryParams.Raw,
    DoptApi.AssistantQueryParams
> = core.serialization.object({
    userIdentifier: core.serialization.string(),
    groupIdentifier: core.serialization.string().optional(),
    model: core.serialization.string().optional(),
});

export declare namespace AssistantQueryParams {
    interface Raw {
        userIdentifier: string;
        groupIdentifier?: string | null;
        model?: string | null;
    }
}
