/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";

export const AssistantDocumentSourcesItemChunksItem: core.serialization.ObjectSchema<
    serializers.AssistantDocumentSourcesItemChunksItem.Raw,
    DoptApi.AssistantDocumentSourcesItemChunksItem
> = core.serialization.object({
    chunkId: core.serialization.number(),
    text: core.serialization.string(),
    score: core.serialization.number(),
});

export declare namespace AssistantDocumentSourcesItemChunksItem {
    interface Raw {
        chunkId: number;
        text: string;
        score: number;
    }
}
