/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";

export const AssistantRequestBodyContextElementValuePosition: core.serialization.ObjectSchema<
    serializers.AssistantRequestBodyContextElementValuePosition.Raw,
    DoptApi.AssistantRequestBodyContextElementValuePosition
> = core.serialization.object({
    top: core.serialization.number(),
    left: core.serialization.number(),
});

export declare namespace AssistantRequestBodyContextElementValuePosition {
    interface Raw {
        top: number;
        left: number;
    }
}
