/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantCompletionsRequestBodyContext } from "./AssistantCompletionsRequestBodyContext";

export const AssistantCompletionsRequestBody: core.serialization.ObjectSchema<
    serializers.AssistantCompletionsRequestBody.Raw,
    DoptApi.AssistantCompletionsRequestBody
> = core.serialization.object({
    query: core.serialization.string().optional(),
    context: AssistantCompletionsRequestBodyContext.optional(),
});

export declare namespace AssistantCompletionsRequestBody {
    interface Raw {
        query?: string | null;
        context?: AssistantCompletionsRequestBodyContext.Raw | null;
    }
}
