/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantSearchRequestBodyContextElementValuePosition } from "./AssistantSearchRequestBodyContextElementValuePosition";

export const AssistantSearchRequestBodyContextElementValue: core.serialization.ObjectSchema<
    serializers.AssistantSearchRequestBodyContextElementValue.Raw,
    DoptApi.AssistantSearchRequestBodyContextElementValue
> = core.serialization.object({
    position: AssistantSearchRequestBodyContextElementValuePosition,
    content: core.serialization.string(),
    tag: core.serialization.string(),
});

export declare namespace AssistantSearchRequestBodyContextElementValue {
    interface Raw {
        position: AssistantSearchRequestBodyContextElementValuePosition.Raw;
        content: string;
        tag: string;
    }
}
