/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantSearchRequestBodyContextVisual: core.serialization.ObjectSchema<
    serializers.AssistantSearchRequestBodyContextVisual.Raw,
    DoptApi.AssistantSearchRequestBodyContextVisual
> = core.serialization.object({
    type: core.serialization.stringLiteral("visual"),
    value: core.serialization.string(),
});

export declare namespace AssistantSearchRequestBodyContextVisual {
    interface Raw {
        type: "visual";
        value: string;
    }
}
