/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantCompletionsRequestBodyContextDocumentValue } from "./AssistantCompletionsRequestBodyContextDocumentValue";

export const AssistantCompletionsRequestBodyContextDocument: core.serialization.ObjectSchema<
    serializers.AssistantCompletionsRequestBodyContextDocument.Raw,
    DoptApi.AssistantCompletionsRequestBodyContextDocument
> = core.serialization.object({
    type: core.serialization.stringLiteral("document"),
    value: AssistantCompletionsRequestBodyContextDocumentValue,
});

export declare namespace AssistantCompletionsRequestBodyContextDocument {
    interface Raw {
        type: "document";
        value: AssistantCompletionsRequestBodyContextDocumentValue.Raw;
    }
}
