/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantCompletionsRequestBody: core.serialization.ObjectSchema<
    serializers.AssistantCompletionsRequestBody.Raw,
    DoptApi.AssistantCompletionsRequestBody
> = core.serialization.object({
    query: core.serialization.string().optional(),
    context: core.serialization
        .lazyObject(async () => (await import("..")).AssistantCompletionsRequestBodyContext)
        .optional(),
});

export declare namespace AssistantCompletionsRequestBody {
    interface Raw {
        query?: string | null;
        context?: serializers.AssistantCompletionsRequestBodyContext.Raw | null;
    }
}
