/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantCompletionsRequestBodyContextElementValuePosition } from "./AssistantCompletionsRequestBodyContextElementValuePosition";

export const AssistantCompletionsRequestBodyContextElementValue: core.serialization.ObjectSchema<
    serializers.AssistantCompletionsRequestBodyContextElementValue.Raw,
    DoptApi.AssistantCompletionsRequestBodyContextElementValue
> = core.serialization.object({
    position: AssistantCompletionsRequestBodyContextElementValuePosition,
    content: core.serialization.string(),
    tag: core.serialization.string(),
});

export declare namespace AssistantCompletionsRequestBodyContextElementValue {
    interface Raw {
        position: AssistantCompletionsRequestBodyContextElementValuePosition.Raw;
        content: string;
        tag: string;
    }
}
