/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantRequestBody: core.serialization.ObjectSchema<
    serializers.AssistantRequestBody.Raw,
    DoptApi.AssistantRequestBody
> = core.serialization.object({
    query: core.serialization.string().optional(),
    context: core.serialization.lazyObject(async () => (await import("..")).AssistantRequestBodyContext).optional(),
});

export declare namespace AssistantRequestBody {
    interface Raw {
        query?: string | null;
        context?: serializers.AssistantRequestBodyContext.Raw | null;
    }
}
