/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantSearchRequestBodyContextDocumentValue } from "./AssistantSearchRequestBodyContextDocumentValue";

export const AssistantSearchRequestBodyContextDocument: core.serialization.ObjectSchema<
    serializers.AssistantSearchRequestBodyContextDocument.Raw,
    DoptApi.AssistantSearchRequestBodyContextDocument
> = core.serialization.object({
    type: core.serialization.stringLiteral("document"),
    value: AssistantSearchRequestBodyContextDocumentValue,
});

export declare namespace AssistantSearchRequestBodyContextDocument {
    interface Raw {
        type: "document";
        value: AssistantSearchRequestBodyContextDocumentValue.Raw;
    }
}
