/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantDocumentSourcesItemChunksItem } from "./AssistantDocumentSourcesItemChunksItem";

export const AssistantDocumentSourcesItem: core.serialization.ObjectSchema<
    serializers.AssistantDocumentSourcesItem.Raw,
    DoptApi.AssistantDocumentSourcesItem
> = core.serialization.object({
    id: core.serialization.number(),
    title: core.serialization.string(),
    url: core.serialization.string(),
    chunks: core.serialization.list(AssistantDocumentSourcesItemChunksItem),
});

export declare namespace AssistantDocumentSourcesItem {
    interface Raw {
        id: number;
        title: string;
        url: string;
        chunks: AssistantDocumentSourcesItemChunksItem.Raw[];
    }
}
