/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantRequestBodyContextDocument: core.serialization.ObjectSchema<
    serializers.AssistantRequestBodyContextDocument.Raw,
    DoptApi.AssistantRequestBodyContextDocument
> = core.serialization.object({
    type: core.serialization.stringLiteral("document"),
    value: core.serialization.lazyObject(async () => (await import("..")).AssistantRequestBodyContextDocumentValue),
});

export declare namespace AssistantRequestBodyContextDocument {
    interface Raw {
        type: "document";
        value: serializers.AssistantRequestBodyContextDocumentValue.Raw;
    }
}
