/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantRequestBodyContextElement: core.serialization.ObjectSchema<
    serializers.AssistantRequestBodyContextElement.Raw,
    DoptApi.AssistantRequestBodyContextElement
> = core.serialization.object({
    type: core.serialization.stringLiteral("element"),
    value: core.serialization.lazyObject(async () => (await import("..")).AssistantRequestBodyContextElementValue),
});

export declare namespace AssistantRequestBodyContextElement {
    interface Raw {
        type: "element";
        value: serializers.AssistantRequestBodyContextElementValue.Raw;
    }
}
