/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantCompletionsResponseSourcesItemChunksItem: core.serialization.ObjectSchema<
    serializers.AssistantCompletionsResponseSourcesItemChunksItem.Raw,
    DoptApi.AssistantCompletionsResponseSourcesItemChunksItem
> = core.serialization.object({
    chunkId: core.serialization.number(),
    text: core.serialization.string(),
    score: core.serialization.number(),
});

export declare namespace AssistantCompletionsResponseSourcesItemChunksItem {
    interface Raw {
        chunkId: number;
        text: string;
        score: number;
    }
}
