/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantCompletionsRequestBodyContextElement: core.serialization.ObjectSchema<
    serializers.AssistantCompletionsRequestBodyContextElement.Raw,
    DoptApi.AssistantCompletionsRequestBodyContextElement
> = core.serialization.object({
    type: core.serialization.stringLiteral("element"),
    value: core.serialization.lazyObject(
        async () => (await import("..")).AssistantCompletionsRequestBodyContextElementValue
    ),
});

export declare namespace AssistantCompletionsRequestBodyContextElement {
    interface Raw {
        type: "element";
        value: serializers.AssistantCompletionsRequestBodyContextElementValue.Raw;
    }
}
