/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantSearchResponse: core.serialization.Schema<
    serializers.AssistantSearchResponse.Raw,
    DoptApi.AssistantSearchResponse
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("..")).AssistantSearchResponseItem)
);

export declare namespace AssistantSearchResponse {
    type Raw = serializers.AssistantSearchResponseItem.Raw[];
}
