/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantRequestBodyContextDocumentValue } from "./AssistantRequestBodyContextDocumentValue";

export const AssistantRequestBodyContextDocument: core.serialization.ObjectSchema<
    serializers.AssistantRequestBodyContextDocument.Raw,
    DoptApi.AssistantRequestBodyContextDocument
> = core.serialization.object({
    type: core.serialization.stringLiteral("document"),
    value: AssistantRequestBodyContextDocumentValue,
});

export declare namespace AssistantRequestBodyContextDocument {
    interface Raw {
        type: "document";
        value: AssistantRequestBodyContextDocumentValue.Raw;
    }
}
