/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantRequestBodyContextSemanticValue } from "./AssistantRequestBodyContextSemanticValue";

export const AssistantRequestBodyContextSemantic: core.serialization.ObjectSchema<
    serializers.AssistantRequestBodyContextSemantic.Raw,
    DoptApi.AssistantRequestBodyContextSemantic
> = core.serialization.object({
    type: core.serialization.stringLiteral("semantic"),
    value: AssistantRequestBodyContextSemanticValue,
});

export declare namespace AssistantRequestBodyContextSemantic {
    interface Raw {
        type: "semantic";
        value: AssistantRequestBodyContextSemanticValue.Raw;
    }
}
