/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantSearchResponseItemChunksItem } from "./AssistantSearchResponseItemChunksItem";

export const AssistantSearchResponseItem: core.serialization.ObjectSchema<
    serializers.AssistantSearchResponseItem.Raw,
    DoptApi.AssistantSearchResponseItem
> = core.serialization.object({
    id: core.serialization.number(),
    title: core.serialization.string(),
    url: core.serialization.string(),
    chunks: core.serialization.list(AssistantSearchResponseItemChunksItem),
});

export declare namespace AssistantSearchResponseItem {
    interface Raw {
        id: number;
        title: string;
        url: string;
        chunks: AssistantSearchResponseItemChunksItem.Raw[];
    }
}
