/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantSearchRequestBodyContextElement: core.serialization.ObjectSchema<
    serializers.AssistantSearchRequestBodyContextElement.Raw,
    DoptApi.AssistantSearchRequestBodyContextElement
> = core.serialization.object({
    type: core.serialization.stringLiteral("element"),
    value: core.serialization.lazyObject(
        async () => (await import("..")).AssistantSearchRequestBodyContextElementValue
    ),
});

export declare namespace AssistantSearchRequestBodyContextElement {
    interface Raw {
        type: "element";
        value: serializers.AssistantSearchRequestBodyContextElementValue.Raw;
    }
}
