/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantCompletionsResponseSourcesItem } from "./AssistantCompletionsResponseSourcesItem";

export const AssistantCompletionsResponse: core.serialization.ObjectSchema<
    serializers.AssistantCompletionsResponse.Raw,
    DoptApi.AssistantCompletionsResponse
> = core.serialization.object({
    answer: core.serialization.string(),
    sources: core.serialization.list(AssistantCompletionsResponseSourcesItem),
});

export declare namespace AssistantCompletionsResponse {
    interface Raw {
        answer: string;
        sources: AssistantCompletionsResponseSourcesItem.Raw[];
    }
}
