/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantSearchRequestBodyContext: core.serialization.ObjectSchema<
    serializers.AssistantSearchRequestBodyContext.Raw,
    DoptApi.AssistantSearchRequestBodyContext
> = core.serialization.object({
    document: core.serialization
        .lazyObject(async () => (await import("..")).AssistantSearchRequestBodyContextDocument)
        .optional(),
    visual: core.serialization
        .lazyObject(async () => (await import("..")).AssistantSearchRequestBodyContextVisual)
        .optional(),
    element: core.serialization
        .lazyObject(async () => (await import("..")).AssistantSearchRequestBodyContextElement)
        .optional(),
    semantic: core.serialization
        .lazyObject(async () => (await import("..")).AssistantSearchRequestBodyContextSemantic)
        .optional(),
});

export declare namespace AssistantSearchRequestBodyContext {
    interface Raw {
        document?: serializers.AssistantSearchRequestBodyContextDocument.Raw | null;
        visual?: serializers.AssistantSearchRequestBodyContextVisual.Raw | null;
        element?: serializers.AssistantSearchRequestBodyContextElement.Raw | null;
        semantic?: serializers.AssistantSearchRequestBodyContextSemantic.Raw | null;
    }
}
