/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantCompletionsRequestBodyContextSemantic: core.serialization.ObjectSchema<
    serializers.AssistantCompletionsRequestBodyContextSemantic.Raw,
    DoptApi.AssistantCompletionsRequestBodyContextSemantic
> = core.serialization.object({
    type: core.serialization.stringLiteral("semantic"),
    value: core.serialization.lazyObject(
        async () => (await import("..")).AssistantCompletionsRequestBodyContextSemanticValue
    ),
});

export declare namespace AssistantCompletionsRequestBodyContextSemantic {
    interface Raw {
        type: "semantic";
        value: serializers.AssistantCompletionsRequestBodyContextSemanticValue.Raw;
    }
}
