/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const AssistantCompletionsResponse: core.serialization.ObjectSchema<
    serializers.AssistantCompletionsResponse.Raw,
    DoptApi.AssistantCompletionsResponse
> = core.serialization.object({
    answer: core.serialization.string(),
    sources: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("..")).AssistantCompletionsResponseSourcesItem)
    ),
});

export declare namespace AssistantCompletionsResponse {
    interface Raw {
        answer: string;
        sources: serializers.AssistantCompletionsResponseSourcesItem.Raw[];
    }
}
