/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { AssistantDocumentSourcesItem } from "./AssistantDocumentSourcesItem";

export const AssistantDocumentSources: core.serialization.Schema<
    serializers.AssistantDocumentSources.Raw,
    DoptApi.AssistantDocumentSources
> = core.serialization.list(AssistantDocumentSourcesItem);

export declare namespace AssistantDocumentSources {
    type Raw = AssistantDocumentSourcesItem.Raw[];
}
