/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const ChatStreamChunkStatus: core.serialization.ObjectSchema<
    serializers.ChatStreamChunkStatus.Raw,
    DoptApi.ChatStreamChunkStatus
> = core.serialization.object({
    status: core.serialization.lazy(async () => (await import("..")).ChatStreamChunkStatusStatus),
});

export declare namespace ChatStreamChunkStatus {
    interface Raw {
        status: serializers.ChatStreamChunkStatusStatus.Raw;
    }
}
