/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const ChatStreamChunkContent: core.serialization.ObjectSchema<
    serializers.ChatStreamChunkContent.Raw,
    DoptApi.ChatStreamChunkContent
> = core.serialization.object({
    content: core.serialization.string(),
});

export declare namespace ChatStreamChunkContent {
    interface Raw {
        content: string;
    }
}
