/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { ChatStreamChunkStatusStatus } from "./ChatStreamChunkStatusStatus";

export const ChatStreamChunkStatus: core.serialization.ObjectSchema<
    serializers.ChatStreamChunkStatus.Raw,
    DoptApi.ChatStreamChunkStatus
> = core.serialization.object({
    status: ChatStreamChunkStatusStatus,
});

export declare namespace ChatStreamChunkStatus {
    interface Raw {
        status: ChatStreamChunkStatusStatus.Raw;
    }
}
