/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { ChatStreamChunkAnswerSourcesItem } from "./ChatStreamChunkAnswerSourcesItem";

export const ChatStreamChunkAnswer: core.serialization.ObjectSchema<
    serializers.ChatStreamChunkAnswer.Raw,
    DoptApi.ChatStreamChunkAnswer
> = core.serialization.object({
    answer: core.serialization.string(),
    sources: core.serialization.list(ChatStreamChunkAnswerSourcesItem),
});

export declare namespace ChatStreamChunkAnswer {
    interface Raw {
        answer: string;
        sources: ChatStreamChunkAnswerSourcesItem.Raw[];
    }
}
