/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";

export const ContentStreamChunk: core.serialization.ObjectSchema<
    serializers.ContentStreamChunk.Raw,
    DoptApi.ContentStreamChunk
> = core.serialization.object({
    type: core.serialization.stringLiteral("content"),
    content: core.serialization.string(),
});

export declare namespace ContentStreamChunk {
    interface Raw {
        type: "content";
        content: string;
    }
}
