/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const DocumentContext: core.serialization.ObjectSchema<
    serializers.DocumentContext.Raw,
    DoptApi.DocumentContext
> = core.serialization.object({
    type: core.serialization.stringLiteral("document"),
    value: core.serialization.lazyObject(async () => (await import("..")).DocumentContextValue),
});

export declare namespace DocumentContext {
    interface Raw {
        type: "document";
        value: serializers.DocumentContextValue.Raw;
    }
}
