/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { DocumentContextValue } from "./DocumentContextValue";

export const DocumentContext: core.serialization.ObjectSchema<
    serializers.DocumentContext.Raw,
    DoptApi.DocumentContext
> = core.serialization.object({
    type: core.serialization.stringLiteral("document"),
    value: DocumentContextValue,
});

export declare namespace DocumentContext {
    interface Raw {
        type: "document";
        value: DocumentContextValue.Raw;
    }
}
