/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { ElementContextValuePosition } from "./ElementContextValuePosition";

export const ElementContextValue: core.serialization.ObjectSchema<
    serializers.ElementContextValue.Raw,
    DoptApi.ElementContextValue
> = core.serialization.object({
    position: ElementContextValuePosition,
    content: core.serialization.string(),
    tag: core.serialization.string(),
});

export declare namespace ElementContextValue {
    interface Raw {
        position: ElementContextValuePosition.Raw;
        content: string;
        tag: string;
    }
}
