/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { ElementContextValue } from "./ElementContextValue";

export const ElementContext: core.serialization.ObjectSchema<serializers.ElementContext.Raw, DoptApi.ElementContext> =
    core.serialization.object({
        type: core.serialization.stringLiteral("element"),
        value: ElementContextValue,
    });

export declare namespace ElementContext {
    interface Raw {
        type: "element";
        value: ElementContextValue.Raw;
    }
}
