/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const SemanticContext: core.serialization.ObjectSchema<
    serializers.SemanticContext.Raw,
    DoptApi.SemanticContext
> = core.serialization.object({
    type: core.serialization.stringLiteral("semantic"),
    value: core.serialization.lazyObject(async () => (await import("..")).SemanticContextValue),
});

export declare namespace SemanticContext {
    interface Raw {
        type: "semantic";
        value: serializers.SemanticContextValue.Raw;
    }
}
