/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { SemanticContextValue } from "./SemanticContextValue";

export const SemanticContext: core.serialization.ObjectSchema<
    serializers.SemanticContext.Raw,
    DoptApi.SemanticContext
> = core.serialization.object({
    type: core.serialization.stringLiteral("semantic"),
    value: SemanticContextValue,
});

export declare namespace SemanticContext {
    interface Raw {
        type: "semantic";
        value: SemanticContextValue.Raw;
    }
}
