/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DoptApi from "../../api/index";
import * as core from "../../core";
import { StatusChunkStatus } from "./StatusChunkStatus";

export const StatusChunk: core.serialization.ObjectSchema<serializers.StatusChunk.Raw, DoptApi.StatusChunk> =
    core.serialization.object({
        type: core.serialization.stringLiteral("status"),
        status: StatusChunkStatus,
    });

export declare namespace StatusChunk {
    interface Raw {
        type: "status";
        status: StatusChunkStatus.Raw;
    }
}
