/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const VisualContext: core.serialization.ObjectSchema<serializers.VisualContext.Raw, DoptApi.VisualContext> =
    core.serialization.object({
        type: core.serialization.stringLiteral("visual"),
        value: core.serialization.string(),
    });

export declare namespace VisualContext {
    interface Raw {
        type: "visual";
        value: string;
    }
}
