/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as DoptApi from "../../../../api/index";
import * as core from "../../../../core";
import { SearchResponseItem } from "../types/SearchResponseItem";

export const Response: core.serialization.Schema<
    serializers.assistant.search.Response.Raw,
    DoptApi.SearchResponseItem[]
> = core.serialization.list(SearchResponseItem);

export declare namespace Response {
    type Raw = SearchResponseItem.Raw[];
}
