/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CompletionsCreateResponseSourcesItemChunksItem } from "./CompletionsCreateResponseSourcesItemChunksItem";

export const CompletionsCreateResponseSourcesItem: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsCreateResponseSourcesItem.Raw,
    DoptApi.assistant.CompletionsCreateResponseSourcesItem
> = core.serialization.object({
    id: core.serialization.number(),
    title: core.serialization.string(),
    url: core.serialization.string(),
    chunks: core.serialization.list(CompletionsCreateResponseSourcesItemChunksItem),
});

export declare namespace CompletionsCreateResponseSourcesItem {
    interface Raw {
        id: number;
        title: string;
        url: string;
        chunks: CompletionsCreateResponseSourcesItemChunksItem.Raw[];
    }
}
