/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const CompletionsStreamRequestContextElementValuePosition: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamRequestContextElementValuePosition.Raw,
    DoptApi.assistant.CompletionsStreamRequestContextElementValuePosition
> = core.serialization.object({
    top: core.serialization.number(),
    left: core.serialization.number(),
});

export declare namespace CompletionsStreamRequestContextElementValuePosition {
    interface Raw {
        top: number;
        left: number;
    }
}
