/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as DoptApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const CompletionsCreateRequestContextSemanticValue: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsCreateRequestContextSemanticValue.Raw,
    DoptApi.assistant.CompletionsCreateRequestContextSemanticValue
> = core.serialization.object({
    semanticContent: core.serialization.string(),
    neighboringSemanticContent: core.serialization.string(),
});

export declare namespace CompletionsCreateRequestContextSemanticValue {
    interface Raw {
        semanticContent: string;
        neighboringSemanticContent: string;
    }
}
