/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CompletionsCreateRequestContextDocumentValue } from "./CompletionsCreateRequestContextDocumentValue";

export const CompletionsCreateRequestContextDocument: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsCreateRequestContextDocument.Raw,
    DoptApi.assistant.CompletionsCreateRequestContextDocument
> = core.serialization.object({
    type: core.serialization.stringLiteral("document"),
    value: CompletionsCreateRequestContextDocumentValue,
});

export declare namespace CompletionsCreateRequestContextDocument {
    interface Raw {
        type: "document";
        value: CompletionsCreateRequestContextDocumentValue.Raw;
    }
}
