/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as DoptApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const CompletionsStreamRequestContext: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamRequestContext.Raw,
    DoptApi.assistant.CompletionsStreamRequestContext
> = core.serialization.object({
    document: core.serialization
        .lazyObject(async () => (await import("../../../../..")).assistant.CompletionsStreamRequestContextDocument)
        .optional(),
    visual: core.serialization
        .lazyObject(async () => (await import("../../../../..")).assistant.CompletionsStreamRequestContextVisual)
        .optional(),
    element: core.serialization
        .lazyObject(async () => (await import("../../../../..")).assistant.CompletionsStreamRequestContextElement)
        .optional(),
    semantic: core.serialization
        .lazyObject(async () => (await import("../../../../..")).assistant.CompletionsStreamRequestContextSemantic)
        .optional(),
});

export declare namespace CompletionsStreamRequestContext {
    interface Raw {
        document?: serializers.assistant.CompletionsStreamRequestContextDocument.Raw | null;
        visual?: serializers.assistant.CompletionsStreamRequestContextVisual.Raw | null;
        element?: serializers.assistant.CompletionsStreamRequestContextElement.Raw | null;
        semantic?: serializers.assistant.CompletionsStreamRequestContextSemantic.Raw | null;
    }
}
