/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const CompletionsStreamRequestContextVisual: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamRequestContextVisual.Raw,
    DoptApi.assistant.CompletionsStreamRequestContextVisual
> = core.serialization.object({
    type: core.serialization.stringLiteral("visual"),
    value: core.serialization.string(),
});

export declare namespace CompletionsStreamRequestContextVisual {
    interface Raw {
        type: "visual";
        value: string;
    }
}
