/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as DoptApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const CompletionsStreamResponseContent: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamResponseContent.Raw,
    DoptApi.assistant.CompletionsStreamResponseContent
> = core.serialization.object({
    content: core.serialization.string(),
});

export declare namespace CompletionsStreamResponseContent {
    interface Raw {
        content: string;
    }
}
