/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CompletionsStreamResponseAnswerSourcesItem } from "./CompletionsStreamResponseAnswerSourcesItem";

export const CompletionsStreamResponseAnswer: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamResponseAnswer.Raw,
    DoptApi.assistant.CompletionsStreamResponseAnswer
> = core.serialization.object({
    answer: core.serialization.string(),
    sources: core.serialization.list(CompletionsStreamResponseAnswerSourcesItem),
});

export declare namespace CompletionsStreamResponseAnswer {
    interface Raw {
        answer: string;
        sources: CompletionsStreamResponseAnswerSourcesItem.Raw[];
    }
}
