/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as DoptApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const CompletionsCreateRequestContextElement: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsCreateRequestContextElement.Raw,
    DoptApi.assistant.CompletionsCreateRequestContextElement
> = core.serialization.object({
    type: core.serialization.stringLiteral("element"),
    value: core.serialization.lazyObject(
        async () => (await import("../../../../..")).assistant.CompletionsCreateRequestContextElementValue
    ),
});

export declare namespace CompletionsCreateRequestContextElement {
    interface Raw {
        type: "element";
        value: serializers.assistant.CompletionsCreateRequestContextElementValue.Raw;
    }
}
