/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as DoptApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const CompletionsCreateRequestContextElementValuePosition: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsCreateRequestContextElementValuePosition.Raw,
    DoptApi.assistant.CompletionsCreateRequestContextElementValuePosition
> = core.serialization.object({
    top: core.serialization.number(),
    left: core.serialization.number(),
});

export declare namespace CompletionsCreateRequestContextElementValuePosition {
    interface Raw {
        top: number;
        left: number;
    }
}
