/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const CompletionsStreamResponseStatusStatus: core.serialization.Schema<
    serializers.assistant.CompletionsStreamResponseStatusStatus.Raw,
    DoptApi.assistant.CompletionsStreamResponseStatusStatus
> = core.serialization.enum_(["searching", "answering"]);

export declare namespace CompletionsStreamResponseStatusStatus {
    type Raw = "searching" | "answering";
}
