/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CompletionsCreateRequestContextElementValuePosition } from "./CompletionsCreateRequestContextElementValuePosition";

export const CompletionsCreateRequestContextElementValue: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsCreateRequestContextElementValue.Raw,
    DoptApi.assistant.CompletionsCreateRequestContextElementValue
> = core.serialization.object({
    position: CompletionsCreateRequestContextElementValuePosition,
    content: core.serialization.string(),
    tag: core.serialization.string(),
});

export declare namespace CompletionsCreateRequestContextElementValue {
    interface Raw {
        position: CompletionsCreateRequestContextElementValuePosition.Raw;
        content: string;
        tag: string;
    }
}
