/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as DoptApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const CompletionsStreamRequestContextDocument: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamRequestContextDocument.Raw,
    DoptApi.assistant.CompletionsStreamRequestContextDocument
> = core.serialization.object({
    type: core.serialization.stringLiteral("document"),
    value: core.serialization.lazyObject(
        async () => (await import("../../../../..")).assistant.CompletionsStreamRequestContextDocumentValue
    ),
});

export declare namespace CompletionsStreamRequestContextDocument {
    interface Raw {
        type: "document";
        value: serializers.assistant.CompletionsStreamRequestContextDocumentValue.Raw;
    }
}
