/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CompletionsCreateRequestContextSemanticValue } from "./CompletionsCreateRequestContextSemanticValue";

export const CompletionsCreateRequestContextSemantic: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsCreateRequestContextSemantic.Raw,
    DoptApi.assistant.CompletionsCreateRequestContextSemantic
> = core.serialization.object({
    type: core.serialization.stringLiteral("semantic"),
    value: CompletionsCreateRequestContextSemanticValue,
});

export declare namespace CompletionsCreateRequestContextSemantic {
    interface Raw {
        type: "semantic";
        value: CompletionsCreateRequestContextSemanticValue.Raw;
    }
}
