/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const CompletionsCreateRequestContextDocumentValue: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsCreateRequestContextDocumentValue.Raw,
    DoptApi.assistant.CompletionsCreateRequestContextDocumentValue
> = core.serialization.object({
    url: core.serialization.string(),
    title: core.serialization.string(),
    width: core.serialization.number(),
    height: core.serialization.number(),
});

export declare namespace CompletionsCreateRequestContextDocumentValue {
    interface Raw {
        url: string;
        title: string;
        width: number;
        height: number;
    }
}
