/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CompletionsCreateRequestContextElementValue } from "./CompletionsCreateRequestContextElementValue";

export const CompletionsCreateRequestContextElement: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsCreateRequestContextElement.Raw,
    DoptApi.assistant.CompletionsCreateRequestContextElement
> = core.serialization.object({
    type: core.serialization.stringLiteral("element"),
    value: CompletionsCreateRequestContextElementValue,
});

export declare namespace CompletionsCreateRequestContextElement {
    interface Raw {
        type: "element";
        value: CompletionsCreateRequestContextElementValue.Raw;
    }
}
