/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as DoptApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const CompletionsCreateRequestContextDocument: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsCreateRequestContextDocument.Raw,
    DoptApi.assistant.CompletionsCreateRequestContextDocument
> = core.serialization.object({
    type: core.serialization.stringLiteral("document"),
    value: core.serialization.lazyObject(
        async () => (await import("../../../../..")).assistant.CompletionsCreateRequestContextDocumentValue
    ),
});

export declare namespace CompletionsCreateRequestContextDocument {
    interface Raw {
        type: "document";
        value: serializers.assistant.CompletionsCreateRequestContextDocumentValue.Raw;
    }
}
