/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CompletionsStreamRequestContextDocument } from "./CompletionsStreamRequestContextDocument";
import { CompletionsStreamRequestContextVisual } from "./CompletionsStreamRequestContextVisual";
import { CompletionsStreamRequestContextElement } from "./CompletionsStreamRequestContextElement";
import { CompletionsStreamRequestContextSemantic } from "./CompletionsStreamRequestContextSemantic";

export const CompletionsStreamRequestContext: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamRequestContext.Raw,
    DoptApi.assistant.CompletionsStreamRequestContext
> = core.serialization.object({
    document: CompletionsStreamRequestContextDocument.optional(),
    visual: CompletionsStreamRequestContextVisual.optional(),
    element: CompletionsStreamRequestContextElement.optional(),
    semantic: CompletionsStreamRequestContextSemantic.optional(),
});

export declare namespace CompletionsStreamRequestContext {
    interface Raw {
        document?: CompletionsStreamRequestContextDocument.Raw | null;
        visual?: CompletionsStreamRequestContextVisual.Raw | null;
        element?: CompletionsStreamRequestContextElement.Raw | null;
        semantic?: CompletionsStreamRequestContextSemantic.Raw | null;
    }
}
