/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CompletionsStreamRequestContextElementValue } from "./CompletionsStreamRequestContextElementValue";

export const CompletionsStreamRequestContextElement: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamRequestContextElement.Raw,
    DoptApi.assistant.CompletionsStreamRequestContextElement
> = core.serialization.object({
    type: core.serialization.stringLiteral("element"),
    value: CompletionsStreamRequestContextElementValue,
});

export declare namespace CompletionsStreamRequestContextElement {
    interface Raw {
        type: "element";
        value: CompletionsStreamRequestContextElementValue.Raw;
    }
}
