/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CompletionsStreamRequestContextElementValuePosition } from "./CompletionsStreamRequestContextElementValuePosition";

export const CompletionsStreamRequestContextElementValue: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamRequestContextElementValue.Raw,
    DoptApi.assistant.CompletionsStreamRequestContextElementValue
> = core.serialization.object({
    position: CompletionsStreamRequestContextElementValuePosition,
    content: core.serialization.string(),
    tag: core.serialization.string(),
});

export declare namespace CompletionsStreamRequestContextElementValue {
    interface Raw {
        position: CompletionsStreamRequestContextElementValuePosition.Raw;
        content: string;
        tag: string;
    }
}
