/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CompletionsStreamRequestContextDocumentValue } from "./CompletionsStreamRequestContextDocumentValue";

export const CompletionsStreamRequestContextDocument: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamRequestContextDocument.Raw,
    DoptApi.assistant.CompletionsStreamRequestContextDocument
> = core.serialization.object({
    type: core.serialization.stringLiteral("document"),
    value: CompletionsStreamRequestContextDocumentValue,
});

export declare namespace CompletionsStreamRequestContextDocument {
    interface Raw {
        type: "document";
        value: CompletionsStreamRequestContextDocumentValue.Raw;
    }
}
