/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as DoptApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const CompletionsCreateRequestContextVisual: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsCreateRequestContextVisual.Raw,
    DoptApi.assistant.CompletionsCreateRequestContextVisual
> = core.serialization.object({
    type: core.serialization.stringLiteral("visual"),
    value: core.serialization.string(),
});

export declare namespace CompletionsCreateRequestContextVisual {
    interface Raw {
        type: "visual";
        value: string;
    }
}
