/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as DoptApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const CompletionsStreamRequestContextElement: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamRequestContextElement.Raw,
    DoptApi.assistant.CompletionsStreamRequestContextElement
> = core.serialization.object({
    type: core.serialization.stringLiteral("element"),
    value: core.serialization.lazyObject(
        async () => (await import("../../../../..")).assistant.CompletionsStreamRequestContextElementValue
    ),
});

export declare namespace CompletionsStreamRequestContextElement {
    interface Raw {
        type: "element";
        value: serializers.assistant.CompletionsStreamRequestContextElementValue.Raw;
    }
}
