/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CompletionsCreateRequestContextDocument } from "./CompletionsCreateRequestContextDocument";
import { CompletionsCreateRequestContextVisual } from "./CompletionsCreateRequestContextVisual";
import { CompletionsCreateRequestContextElement } from "./CompletionsCreateRequestContextElement";
import { CompletionsCreateRequestContextSemantic } from "./CompletionsCreateRequestContextSemantic";

export const CompletionsCreateRequestContext: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsCreateRequestContext.Raw,
    DoptApi.assistant.CompletionsCreateRequestContext
> = core.serialization.object({
    document: CompletionsCreateRequestContextDocument.optional(),
    visual: CompletionsCreateRequestContextVisual.optional(),
    element: CompletionsCreateRequestContextElement.optional(),
    semantic: CompletionsCreateRequestContextSemantic.optional(),
});

export declare namespace CompletionsCreateRequestContext {
    interface Raw {
        document?: CompletionsCreateRequestContextDocument.Raw | null;
        visual?: CompletionsCreateRequestContextVisual.Raw | null;
        element?: CompletionsCreateRequestContextElement.Raw | null;
        semantic?: CompletionsCreateRequestContextSemantic.Raw | null;
    }
}
