/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const CompletionsStreamRequestContextSemanticValue: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamRequestContextSemanticValue.Raw,
    DoptApi.assistant.CompletionsStreamRequestContextSemanticValue
> = core.serialization.object({
    semanticContent: core.serialization.string(),
    neighboringSemanticContent: core.serialization.string(),
});

export declare namespace CompletionsStreamRequestContextSemanticValue {
    interface Raw {
        semanticContent: string;
        neighboringSemanticContent: string;
    }
}
