/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CompletionsStreamResponseAnswerSourcesItemChunksItem } from "./CompletionsStreamResponseAnswerSourcesItemChunksItem";

export const CompletionsStreamResponseAnswerSourcesItem: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamResponseAnswerSourcesItem.Raw,
    DoptApi.assistant.CompletionsStreamResponseAnswerSourcesItem
> = core.serialization.object({
    id: core.serialization.number(),
    title: core.serialization.string(),
    url: core.serialization.string(),
    chunks: core.serialization.list(CompletionsStreamResponseAnswerSourcesItemChunksItem),
});

export declare namespace CompletionsStreamResponseAnswerSourcesItem {
    interface Raw {
        id: number;
        title: string;
        url: string;
        chunks: CompletionsStreamResponseAnswerSourcesItemChunksItem.Raw[];
    }
}
