/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as DoptApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const CompletionsStreamResponseAnswer: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamResponseAnswer.Raw,
    DoptApi.assistant.CompletionsStreamResponseAnswer
> = core.serialization.object({
    answer: core.serialization.string(),
    sources: core.serialization.list(
        core.serialization.lazyObject(
            async () => (await import("../../../../..")).assistant.CompletionsStreamResponseAnswerSourcesItem
        )
    ),
});

export declare namespace CompletionsStreamResponseAnswer {
    interface Raw {
        answer: string;
        sources: serializers.assistant.CompletionsStreamResponseAnswerSourcesItem.Raw[];
    }
}
