/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as DoptApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const CompletionsStreamResponseStatus: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamResponseStatus.Raw,
    DoptApi.assistant.CompletionsStreamResponseStatus
> = core.serialization.object({
    status: core.serialization.lazy(
        async () => (await import("../../../../..")).assistant.CompletionsStreamResponseStatusStatus
    ),
});

export declare namespace CompletionsStreamResponseStatus {
    interface Raw {
        status: serializers.assistant.CompletionsStreamResponseStatusStatus.Raw;
    }
}
