/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CompletionsStreamResponseStatusStatus } from "./CompletionsStreamResponseStatusStatus";

export const CompletionsStreamResponseStatus: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsStreamResponseStatus.Raw,
    DoptApi.assistant.CompletionsStreamResponseStatus
> = core.serialization.object({
    status: CompletionsStreamResponseStatusStatus,
});

export declare namespace CompletionsStreamResponseStatus {
    interface Raw {
        status: CompletionsStreamResponseStatusStatus.Raw;
    }
}
