/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as DoptApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { CompletionsCreateResponseSourcesItem } from "./CompletionsCreateResponseSourcesItem";

export const CompletionsCreateResponse: core.serialization.ObjectSchema<
    serializers.assistant.CompletionsCreateResponse.Raw,
    DoptApi.assistant.CompletionsCreateResponse
> = core.serialization.object({
    answer: core.serialization.string(),
    sources: core.serialization.list(CompletionsCreateResponseSourcesItem),
});

export declare namespace CompletionsCreateResponse {
    interface Raw {
        answer: string;
        sources: CompletionsCreateResponseSourcesItem.Raw[];
    }
}
